kind: CronJob
apiVersion: batch/v1
metadata:
  name: demo-cronjob
  namespace: nginx
spec:
  schedule: "*/1 * * * * "
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-container
              image: busybox:latest
              command: ["sh","-c","echo Hello from CronJob && date"]
          restartPolicy: Never


